# Use an official Alpine runtime as a parent image
FROM alpine:latest


# Set the working directory in Docker
WORKDIR /app

# Update and install dependencies
RUN apk update && \
    apk add --no-cache \
    bash \
    build-base \
    curl \
    zip \
    cmake \
    llvm \
    clang \
    ninja \
    git \ 
    mesa-dev \
    libx11-dev \
    libxcb-dev && \
    git clone https://github.com/microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh && \
    rm -rf /var/cache/apk/*

ENV CMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake
