# Use an official Ubuntu runtime as a parent image
FROM ubuntu:latest

# Set the working directory in Docker
WORKDIR /app

# Update and install dependencies
RUN apt-get update && \
    apt-get install -y \
    bash \
    build-essential \
    curl \
    zip \
    cmake \
    llvm \
    clang \
    ninja-build \
    git \
    libx11-dev \
    libxcb1-dev \
    libxinerama-dev \
    libxcursor-dev \
    xorg-dev \
    libglu1-mesa-dev \
    pkg-config && \
    git clone https://github.com/microsoft/vcpkg.git && \
    ./vcpkg/bootstrap-vcpkg.sh && \
    rm -rf /var/lib/apt/lists/*  # Clean up the apt cache to reduce the image size

# Update PATH and set CMAKE_TOOLCHAIN_FILE environment variable
ENV PATH="/app/vcpkg:${PATH}"
ENV CMAKE_TOOLCHAIN_FILE=/app/vcpkg/scripts/buildsystems/vcpkg.cmake
